Add edit function for filter
crest-cassia/oacis pull request #727
Opened 2021-01-27 06:30 UTC by yusiro-bps

refs: https://github.com/crest-cassia/oacis/issues/715

ParameterSet のテーブルにおけるフィルターを編集できるようにしました。

![Untitled](https://user-images.githubusercontent.com/49134429/105951200-0426db80-60b3-11eb-8716-267658dfeb24.gif)

## Validation

#### フィルター名が空欄の場合

![image](https://user-images.githubusercontent.com/49134429/105951547-90390300-60b3-11eb-9a11-3a36c993e3c2.png)

#### フィルター名が他と重複している場合

![image](https://user-images.githubusercontent.com/49134429/105951659-bf4f7480-60b3-11eb-8af5-936c8fd4e55a.png)

#### 条件の値が空欄の場合

![image](https://user-images.githubusercontent.com/49134429/105951682-c70f1900-60b3-11eb-8c68-4acfa7121859.png)

2021-01-27 06:37 UTC, yusiro-bps commented on app/controllers/simulators_controller.rb
> +    redirect_back(fallback_location: simulator)
検索条件などあれば引き継ぐようにしています。

2021-01-27 06:38 UTC, yusiro-bps commented on app/datatables/parameter_set_filters_list_datatable.rb
> +      edit = (OACIS_ACCESS_LEVEL >= 1) ?
削除と同じようにOACIS_ACCESS_LEVEL >= 1 の場合のみ、変更できるようにしています。このあたり認識違っていましたらご指摘お願いします。

2021-01-27 06:38 UTC, yusiro-bps commented on app/views/simulators/_filter_update_form.html.haml
> +        if(data && form.data('raw-fname') != data["name"]) {
同じ名前のフィルターが存在する場合、更新できないようにしています。

2021-01-28 02:10 UTC, yohm requested changes
上の画像のように検索条件が２つ（benefit==3, Nsigma==100) あるときに編集ボタンを押すと、下の画像のように一つの条件しか出てきません。すべての検索条件が出るようにしていただけないでしょうか？

<img width="597" alt="Screen Shot 2021-01-28 at 11 06 59" src="https://user-images.githubusercontent.com/718731/106079697-0d6a8380-6159-11eb-8f95-6966b08193ec.png">


<img width="601" alt="Screen Shot 2021-01-28 at 11 08 06" src="https://user-images.githubusercontent.com/718731/106079734-1f4c2680-6159-11eb-88c0-5c36cc64688a.png">


---

実はプラスアイコンをクリックすると検索条件が追加できます。（わかりづらくてすみません。。。）
<img width="598" alt="Screen Shot 2021-01-28 at 11 24 23" src="https://user-images.githubusercontent.com/718731/106081157-c3cf6800-615b-11eb-8363-1a14b5ce8ef9.png">

2021-01-28 02:10 UTC, yohm commented on app/datatables/parameter_set_filters_list_datatable.rb
> +      edit = (OACIS_ACCESS_LEVEL >= 1) ?
この認識であっています。ありがとうございます 🙏

2021-01-28 02:26 UTC, yohm commented on app/views/simulators/_filter_update_form.html.haml
> +        if(data && form.data('raw-fname') != data["name"]) {
ありがとうございます！

2021-01-28 06:56 UTC, yusiro-bps commented
ご指摘ありがとうございます。

以下、対応しました。
- 全ての条件を更新できるようにする
- 条件を追加できる
- 条件を削除できる

![Untitled](https://user-images.githubusercontent.com/49134429/106100732-2cc8d700-6180-11eb-8307-f1dfb87b6a32.gif)

2021-01-29 03:04 UTC, yohm approved these changes
ご対応ありがとうございました！

2021-01-29 03:04 UTC, merged