Improve ParameterSet table UI
crest-cassia/oacis pull request #729
Opened 2021-02-04 07:53 UTC by yusiro-bps

refs: https://github.com/crest-cassia/oacis/issues/716

### 対応内容

- [x] 列を並び替えられるようにする
- [x] スクロールしてもパラメータの名前が表示されるようにする
- [x] 画面上部にも次のページ、前のページに移動するボタンをつける
- [ ] 値の大小の順位に応じてセルの色をグラデーションする
- [ ] パラメータカラムのみ並び替えできるようにする

2021-02-09 07:42 UTC, yusiro-bps commented on app/datatables/parameter_sets_list_datatable.rb
> +  HUE_MAX = 215
HSLでセルの色を指定するようにしました。
値が大きいものから小さいものへ、赤(0)から青(215)に変化するようにしています(青が濃すぎると数値が見辛くなるので適当に215を最大値として設定しています)。

2021-02-09 07:42 UTC, yusiro-bps commented on app/datatables/parameter_sets_list_datatable.rb
> +    data = []
列の並び替え後にサーバ側とフロント側で並び順の整合性を取るため、dataの形を以下のような形に変えています。

```json
"data": [
    {
      "Checkbox": "...",
      "Progress": "...",
      "ParamsSetID": "...",
      "Updated_at": "...",

    },
    {
      "Checkbox": "...",
      "Progress": "...",
      "ParamsSetID": "...",
      "Updated_at": "...",

    },
  ]
```

2021-02-09 07:42 UTC, yusiro-bps commented on app/datatables/parameter_sets_list_datatable.rb
>          if @base_ps
List of Similar Parameter Sets のテーブルでは、数値に色がつくようなので、セルに色はつけていませんが、必要であればお知らせください。

2021-02-10 01:11 UTC, yohm commented on app/datatables/parameter_sets_list_datatable.rb
> +  HUE_MAX = 215
ありがとうございます。セルへの色付けイメージ通りです。
色をもう少し全般的に透明度をつけて薄い色にしていただけますか？背景がうっすらと色付けされているくらいで良いかと思います。

2021-02-10 01:12 UTC, yohm commented on app/datatables/parameter_sets_list_datatable.rb
>          if @base_ps
おっしゃる通り、必要ないと思います。現状のままでお願いします

2021-02-10 01:43 UTC, yusiro-bps commented on app/datatables/parameter_sets_list_datatable.rb
> +  HUE_MAX = 215
コメントありがとうございます。hslaの透明度を0.3で設定してみました。

![image](https://user-images.githubusercontent.com/49134429/107452402-7821b300-6b8c-11eb-9d8a-e4d909e8acc1.png)

2021-02-10 01:47 UTC, yusiro-bps commented on app/assets/stylesheets/custom.css.scss
> +table.dataTable.fixed_thead thead th {
https://datatables.net/extensions/fixedheader という拡張機能があるのですが、それを使うと、チェックボックス全選択が効かなくなったり、別タブを開いた際にヘッダーが残るようだったので、CSSで固定しています。

2021-02-10 01:55 UTC, yusiro-bps commented on app/assets/javascripts/parameter_set.js
> +        d.sort_column = data ? data['order'][0][0] : null;
列並び替えのあと、列ソートした際にサーバ側でフロント側で指定した列を識別できるようにソート対象列のindexを新しくパラメータとして追加しています。

2021-02-11 08:55 UTC, yohm requested changes
試しに使ってみましたが、おかげさまでとても使いやすくなっています！１点だけ非常に細かい点ですがコメントしました。

2021-02-11 08:55 UTC, yohm commented on app/datatables/parameter_sets_list_datatable.rb
> +    data = []
Simulatorが持つパラメータの定義として "Checkbox", "Progress"などの文字をとることも原理的にはできるので、ここを重複しないようにできないでしょうか？（"Progress" はパラメータの定義としてありうるかもしれないので）
パラメータの定義は letter, number, underscore しかとることができないので、"Progress" を "-Progress" などのようにすれば一意性を保証できます。

2021-02-12 01:03 UTC, yusiro-bps commented on app/datatables/parameter_sets_list_datatable.rb
> +    data = []
ご指摘ありがとうございます。固定カラムは"-"を先頭につけるように修正しました。

2021-02-12 01:56 UTC, yohm approved these changes
ありがとうございます！

2021-02-12 01:56 UTC, merged