Add finished and unfinished Runs tabs in simulators#:id
crest-cassia/oacis pull request #733
Opened 2021-02-19 01:42 UTC by morimorihoge

simulators#showページに `Finished Runs` 及び `Unfinished Runs` を追加 refs #717 

* [x] simulators#showにタブを追加
* [x] runs#_jobs_table がsimulator_idを引数に取れるように修正

![image](https://user-images.githubusercontent.com/818249/108444833-b743b880-729e-11eb-86c9-2e5ed27ea080.png)

## 要確認

* 扱い的にAnalysesもUnifished / Finished共に表示するのが良いか確認し、必要なら実装する

2021-02-19 01:43 UTC, morimorihoge commented
@yohm Finished / Unfinished Runsが表示されるようにしてみました。スクリーンショットはPR descriptionの通りです。

一点、Analysesも表示した方が良さそうな気がしたので、そちらの対応も必要か、確認お願いいたします 🙇‍♂️

2021-02-19 01:53 UTC, morimorihoge commented on app/controllers/runs_controller.rb
> +    conditions[:simulator_id] = params["simulator_id"] if params["simulator_id"].present?
optionalな引数として `simulator_id` を渡せるように更新しています

2021-02-19 01:54 UTC, morimorihoge commented on app/views/simulators/_finished_runs_list.html.haml
> +  });
この辺のloadingコードはshowの方にまとめても良かったのですが、参照しているElement idが同じファイル内に見えていた方が可読性としては良いかなと思い、それぞれのpartial側で呼び出すようにしています。

2021-02-19 02:04 UTC, morimorihoge commented
定例にて、Analysesは表示不要とのこと（Progressも同様なので、それに従う）を確認頂いたので、テストコードを増やした上でDraftを外す方向で対応させて頂きます。

2021-02-25 23:52 UTC, morimorihoge commented
@yohm こちら、テストコードの方追加いたしましたのでmerge readyになります。  
後確認よろしくお願いいたします 🙇‍♂️

2021-02-26 01:50 UTC, yohm requested changes
#732 の変更への追従をお願いします :bow:

2021-02-26 01:50 UTC, yohm commented on app/views/simulators/_finished_runs_list.html.haml
> +    const oFinishedRunsTable = datatables_for_runs_table('#finished_runs_list');
#732 の更新によって関数名が`OACIS` の名前空間に移動しています。こちらのご対応お願いしてもよろしいでしょうか？（最新のdevelopにrebaseしてもらった方がいいかも）

2021-02-26 01:50 UTC, yohm commented on app/views/simulators/_unfinished_runs_list.html.haml
> +    const oUnfinishedRunsTable = datatables_for_runs_table('#unfinished_runs_list');
こちらも`OACIS`名前空間に移動しています。

2021-02-26 02:02 UTC, morimorihoge commented on app/views/simulators/_unfinished_runs_list.html.haml
> +    const oUnfinishedRunsTable = datatables_for_runs_table('#unfinished_runs_list');
こちら、対応＆確認の上修正いたします。

2021-02-26 07:15 UTC, yohm approved these changes

2021-02-26 07:15 UTC, merged